name: Data Science Project Proposal
title: "[Project]: NAME"
description: Use this template to propose new CHAOSS data science projects
labels: ['project', 'proposal']

body:
  - type: markdown
    attributes:
      value: | 
        The CHAOSS Data Science Community is interested in collaboratively working together on projects. The goal is to build a community of active data scientists within the CHAOSS project who are using CHAOSS data to help answer questions. To get the most value out of a CHAOSS Data Science Initiative, we need to scale our data science efforts and share best practices for using data science-based approaches to understanding project health. This requires building a diverse and inclusive community of people with different ideas, perspectives, and skills who can help define and promote our data science efforts. This will allow us to provide value as a project by using CHAOSS data and data science approaches to answer questions from the other WGs and elsewhere within the CHAOSS community while also allowing people to get more real world data science experience.

  - type: markdown
    attributes:
      value: |
        ## Project Information

  - type: input
    attributes:
      label: Project Name (1 - 3 words)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Provide summary of this project including the question you hope to answer and how the question is important for the CHAOSS community
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related Links
      description: If you have already created additional documents or have other information about this project, please include those links here. 
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Note that we also have a [Project Scope Template doc](https://docs.google.com/document/d/13iLNDfqJ8nuwBGEyJuFutcT7KRNT6JwFrSlJN_5f4o4/edit) that you can use to think about the project details if you find it useful (not required).

  - type: dropdown
    attributes:
      label: How would you like to be involved in this project?
      options:
        - I am interested in this project, but do not plan to work on it myself
        - I have the experience and time available to lead this project
        - I would like to help with this project, but would prefer for someone else to lead it
        - Other (please specify in the “Additional Notes” at the end of this form)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Notes.
    validations:
      required: false
